# Unit 4: Good Programming Practices

# Lecture 8: Exceptions And Assertions

## 4.6 Exceptions

- what happens when a procedure hits an **unexpected condition**?
- get an **exception** to what was expected (from the interpreter's perspective)
    - trying to access beyond list limits
        - `IndexError`
    - trying to convert an inappropriate type
        - `TypeError`
    - referencing a non-existent variable
        - `NameError`
    - mixing data types without coercion
        - `TypeError`

---
### Other Types Of Exceptions
---

- already seen in common error types:
    - `SyntaxError`
        - Python interpreter can't parse program
    - `NameError`
        - local or global name not found
    - `AttributeError`
        - attribute reference fails
    - `TypeError`
        - operand doesn't have correct type
    - `ValueError`
        - operand type okay, but value is illegal
    - `IOError`
        - IO systems reports malfunction (e.g. file not found)

---
### What To Do With Exceptions
---

- what to do when we we encounter an error?
    - **fail silently**
        - substitute default values or just continue
        - ***bad*** idea! user gets no warning
    - return an **error value** (aka error code)
        - what value to choose?
        - complicates code having to check for a special value
    - stop execution, **signal error** condition
        - in Python: **raise an exception**
        - `raise Exception("descriptive string")`
            - this is what the interpreter is doing in the background when it throws you a `SyntaxError` or other

---
### Dealing With Exceptions
---

- Python code can provide **handlers** for exceptions
```python
try:
    a = int(input('Tell me one number: '))
    b = int(input('Tell me another number: '))
    print(a/b)
    print('Okay')
except:
    print('Bug in user input')
print('Outside')
```
- exceptions **raised** by any statement in body of `try` are **handled** by the `except` statement and execution continues after the body of the `except` statement

---
### Handling Specific Exceptions
---

- have **separate `except` clauses** to deal with particular types of exceptions
```python
try:
    a = int(input('Tell me one number: '))
    b = int(input('Tell me another number: '))
    print('a/b = ', a/b)
    print('a+b = ', a+b)
except ValueError:
    print('Could not convert to a number.')     # only executes if ValueError exception raised
except ZeroDivisionError:
    print('Cannot divide by zero')              # only executes if ZeroDivisionError exception raised
except:
    print('Something went very wrong.')         # default case to handle any/all other exceptions
```

---
### Other Exceptions
--- 

- `else`:
    - body of this is executed when execution of associated `try` body **completes with no exceptions**
- `finally`:
    - body of this is **always executed** after `try`, `else` and `except` clauses, even if they raised another error or executed a `break`, `continue`, or `return`
    - useful for clean-up code that should be run no matter what else happened (e.g. closing a file so that it's not left hanging, open)
    - lets us specify sets of things we'll do independent of what happens in the `try` loop


---

## 4.7 Exceptions Example

Some examples of how the ability to handle exceptions lets us, for example, control the input to a procedure.  

```python
# loop only exits when correct type of input provided, only prints message if ValueError exception raised
while True:
    try:
        n = input("Please enter an integer: ")
        n = int(n)
        break
    except ValueError:
        print("Input not an integer; try again!")
print("Correct input of an integer!")
```

---
### Example: Controlling Input
---

```python
data = []
file_name = input('Provide a name of a file or data: ')

try:
    fh = open(file_name, 'r')
except IOError:
    print('Cannot open file", file_name)
else:
    for new in fh:
        if new != '\n':
            addIt = new[:-1].split(',')     # remove trailing \n
            data.append(addIt)
    fh.close()
```

---
### Example: Control Input
---

- appears to correct read-in data, and convert to a list of lists
- now suppose we want to restructure this into a list of names and a list of grades for each entry in the overall list
```python
data = []
file_name = input('Provide name of a file: ')

try:
    fh = open(file_name, 'r')
except IOError:
    print('Cannot open', file_name)
else:
    for new in fh:
        if new != '\n':
            addIt = new[:-1].split(',')
            data.append(addIt)
    fh.close()

gradesData = []
if data:
    for student in data:
        try:
            gradesData.append([student[0:2], student[2]])       # handles case of no grade, but assumes two names!
        except IndexError:
            gradesData.append([student[0:2], []])
```
- the above works if we have standard form, including case of no grade
- still fails if names are not two parts long
```python
data = []
file_name = input('Provide name of a file: ')

try:
    fh = open(file_name, 'r')
except IOError:
    print('Cannot open', file_name)
else:
    for new in fh:
        if new != '\n':
            addIt = new[:-1].split(',')
            data.append(addIt)
    fh.close()

gradesData = []
if data:
    for student in data:
        try:
            name = student[0:-1]
            grades = int(student[-1])
            gradesData.append([name, [grades]])
        except ValueError:
            gradesData.append([student[:], []])
```

---

## 4.8 Exceptions As Control Flow

- don't return special values when an error occurred, and then check if an *error value* was returned
- instead, **raise an exception** when unable to produce a result consistent with function's specification
    - `raise <exceptionName>(<arguments>)`
    - `raise ValueError('something is wrong')`
        - raise is a keyword
        - `ValueError` is the name of the you want to raise in this case (typically an existing error exception rather than one we create ourselves)
        - then, a message to print out (which should tell you the specifics of what was going on when that exception was raised)
- puts you in control of deciding when to raise an exception

---
### Example: Raising An Exception
---

```python
def getRatios(L1, L2):
    """
    Assumes: L1 and L2 are lists of equal length of numbers
    Returns: a list containing L1[i]/L2[i]
    """
    ratios = []
    for index in range(len(L1)):
        try:
            ratios.append(L1[index]/float(L2[index]))
        except ZeroDivisonError:
            ratios.append(float('NaN'))     # NaN is Not a Number
        except:
            raise ValueError('getRatios called with bad arg')
    return ratios
```

---
### Example Of Exceptions
---

- assume we are **given a class list** for each subject: each entry is a list of two parts
    - a list of first and last names for a student
    - a list of grades on assignments
```python
test_grades = [[['peter', 'parker'], [80.0, 70.0, 85.0]], 
               [['bruce', 'wayne'], [100.0, 80.0, 74.0]]]
```
- create a **new class list**; with names, grades, and an average
```python
[[['peter', 'parker'], [80.0, 70.0, 85.0], 78.33333],
[['bruce', 'wayne'], [100.0, 80.0, 74.0], 84.666667]]]
```
---
### Example Code
---
```python
def get_stats(class_list):
    new_stats = []
    for elt in class_list:
        new_stats.append([elt[0], elt[1], avg(elt[1])])
    return new_stats

def avg(grades):
    return sum(grades)/len(grades)
```
- this code works, but raises an exception if one or more students **don't have any grades**
- the error is a `ZeroDivisionError: float division by zero` because we tried to `return sum(grades)/len(grades)` while `len(grades)` is 0

---
### Option 1: Flag Error By Printing Message
---

- decide to **notify** that something went wrong with a msg
```python
def avg(grades):
    try:
        return sum(grades)/len(grades)
    except ZeroDivisionError:
        print('no grades data')
```
- running avg with these additions will allow the program to effectively "skip" over the computations it cannot complete, printing our error message instead of a result upon iteration

- this effectively illustrates how we can use our own ability to raise *and/or* handle errors to deal with things in a manner for which we intend, rather than stopping execution

---

## 4.9 Assertions

- want to be sure that **assumptions** on the state of computation are as expected
    - think ahead on things that might occur that might not be what I normally expect or thought about wanting to do in that case
- use an **`assert` statement** to raise an `AssertionError` exception if assumptions not met
- an example of good **defensive programming**

---
### Example
---

```python
def avg(grades):
    assert not len(grades) == 0, 'no grades data'
    return sum(grades)/len(grades)
```
- raises an `AssertionError` if it is given an empty list for grades, otherwise running alright
- this is a simple way of enforcing the expectation I have for this function
    - nice thing to have, because the execution of the procedure stops immediately if the assertion is not met, as opposed to partway through the processing 

---
### Assertions As Defensive Programming
---

- assertions don't allow a programmer to control response to unexpected conditions
    - they ensure that **execution halts** whenever an unexpected condition is not met
- typically used to **check inputs** to functions procedures, but can be used anywhere
- can be used to **check outputs** of a function to avoid propagating bad value(s)
- can make it easier to locate the source of a bug

> "You'll often see in good programming, every function or critical function will have an assertion at the beginning saying that here is what I expect in terms of the form of the input before it comes out. ... If we want to be really careful, we can use it to check outputs before I return a value from the function."  

---
### Where To Use Assertions
---

- goal is to spot bugs as soon as introduced and make clear where they happened
- use as a supplement to testing
- raise **exceptions** if users supply **bad data input(s)**
- use **assertions** to:
    - check **types** of args or values
    - check that **invariants** on data structures are met
    - check **constraints** on return values
    - check for **violations** of constraints on procedure 
        - e.g. no duplicates in a list; if I don't want them, I can enforce that by actually doing a check and raising -- or using an assertion, rather -- to stop the execution if I get to that point

> In Summary:  
> - Exceptions
>     - control flow of processing through a procedure
> - Assertions
>     - check conditions on inputs; outputs; and, potentially, intermediate values

---